### ISSUE TITLE
[FEATURE REQUEST] Meta Events: Callback URL for Convoy's events.

### ISSUE THREAD

**Issue by Subomi** [frain-dev/convoy#1020]
**Describe Feature**
Convoy as a service should be able to publish webhook events about its webhook events.

**Why?** 
One use-case is when implementing the app portal, especially for users who have a dashboard already, not everyone wants to always have to call Convoy's API. They'd prefer to get notified about certain entities and show their users. Entities like: 
- Subscriptions Status
- EventDelivery Status

**Comment by iambenkay** [comment]
I am interested in working on this.

**Comment by Subomi** [comment]
Hey @iambenkay, great! Thank you for your interest in contributing. 

You can go ahead to raise a PR. :)

**Comment by Subomi** [comment]
@horlah I added the dashboard tag to it.
