### ISSUE TITLE
[BUG] Retrying Discarded event deliveries get stuck when endpoint has not been re-activated.

### ISSUE THREAD

**Issue by Subomi** [frain-dev/convoy#1092]
When an endpoint is disabled, all subsequent event deliveries go straight into the discarded state. The Ideal flow is once the endpoint has been fixed, we should retry all discarded events. To re-activate an endpoint, we need to retry one failed event delivery. Ideally, this should work for any failed event delivery, whether `Failed` or `Discarded`. But when `Discarded` event deliveries are re-tried to re-activate an endpoint, they get stuck in the `Processing` state.

Extra Notes
Event Deliveries with zero retries will retry once & get stuck in `Processing` upon failure.

**Comment by Subomi** [comment]
After debugging with @danvixent, we concluded that the core problem here is we are coordinating two status fields: one on the endpoint and the other on the subscription. This results in a few other bugs:

1. When both endpoint & subscription are disabled, and we retry discarded events, only the subscription is set back to active, endpoint stays disabled.
2. When an endpoint has been disabled, the UI still shows `enabled` on the endpoint.
3. When the endpoint is disabled, and the event deliveries are discarded, we retry the event delivery. It goes through, but the endpoint isn't set back to `enabled`.

We do not have any utility for status information on subscriptions, only endpoints.

**Comment by danvixent** [comment]
@Subomi i have opened a pr for the current problem, we will need to decide whether we want to remove the subscription status still.
