### ISSUE TITLE
Not able to use CLI key to send event

### ISSUE THREAD

**Issue by NanFengCheong** [frain-dev/convoy#1190]
I am trying to use CLI key in the api key and I am getting some error.

```
const { Convoy } = require("convoy.js");
const convoy = new Convoy({
  api_key:
    "CO.oYagT4PctoKFmtK8.B4Bj00HHQQ33AWx6BFKnHZ2NYm7eSuDuaOyyuYvFSMfAfIVNeKeCcxM5iaClOLLD",
  uri: "http://localhost:5005/api/v1/events",
});

const appId = "1c38c5cf-f3b1-44ce-b41a-5f3b55033b6f";

async function start() {
  try {
    const eventData = {
      app_id: appId,
      event_type: "payment.success",
      data: {
        event: "payment.success",
        data: {
          status: "Completed2",
          description: "Transaction Successful2",
          userID: "test_user_id8082",
        },
      },
    };

    const response = await convoy.events.create(eventData);
    console.log(response);
  } catch (error) {
    console.log(error);
  }
}

start();
```

Returned result:
`[Error: groupID query is missing] { statusCode: 400 }
`

**Comment by Dotunj** [comment]
Hi @NanFengCheong you can't use the CLI Key to authenticate against the REST API. You need a Project API Key for that. The `uri` field is also wrong. It should be `http://localhost:5005/api/v1`

**Comment by NanFengCheong** [comment]
Hi @Dotunj, what if I wanted to rotate the Project API key, is it possible to do that?

**Comment by Dotunj** [comment]
Hi @NanFengCheong that's not possible at the moment, but there are plans to support it.

**Comment by NanFengCheong** [comment]
Noted. Thanks for answering the questions.
