### ISSUE TITLE
[FEATURE REQUEST] Filter by HTTP Headers 

### ISSUE THREAD

**Issue by Subomi** [frain-dev/convoy#1211]
**Problem Description**
Currently, our filters work exclusively for the webhook payload. With webhook events, some information is stored only in the headers. E.g. For GitHub, the type is saved in the header `X-Github-Event`. 

**Solution**
We should extend our filtering logic to filter for HTTP Header Values.

**Requirements**

- [ ] Add a tab to create a filter for headers in the Filter Editor.
- [ ] Add a view for `Headers` in the `Event Log`
- [x] Updated the endpoint to support sending and testing headers

**Comment by horlah** [comment]
@jirevwe The header detail is not returned in the events log response.
