### ISSUE TITLE
[ENHANCEMENT] Frictionless Onboarding.

### ISSUE THREAD

**Issue by Subomi** [frain-dev/convoy#1222]
**Problem Description**
Convoy's onboarding should be frictionless. A random user should be able to sign up and go to "a ha" moment as quickly as possible.

**Solution**
Walkthrough our Posthog recordings to find drop-off points and pages that are hard to understand to help users easily adopt Convoy. 

**Requirements**

- [x] Remove localhost from events being tracked on Posthog.
- [x] Source creation form for incoming projects should assume `Ingestion HTTP` and not show any more options.
- [x] Incoming Projects Onboarding should be: `Create Source`, `Create Endpoint`, and `Create Subscription`.
- [x] [Design & Frontend] Rework Subscription Time & Duration Forms.
- [x] [Frontend] Remove the Verification Email Page after signing up.
- [x] [Frontend] Assert that errors are shown on all invalid form fields.
- [x] [Backend] Events Dashboard Graph uses `Events` instead of `Event Deliveries`.
- [x] [Backend] Do not log users out while they are using the application.
- [x] [Frontend] Use refresh token to keep users logged in
- [x] [Copy] Improve Copy for Incoming & Outgoing Projects for onboarding and various sections of the dashboard.

**Comment by horlah** [comment]
@Subomi The seventh item here, isn't it a backend issue?
 
I think the endpoint feeding the dashboard is a summary endpoint.
