### ISSUE TITLE
v0.8.0 is missing from docker versions

### ISSUE THREAD

**Issue by NanFengCheong** [frain-dev/convoy#1252]
Couldnt find docker with version v0.8.0
https://cloudsmith.io/~convoy/repos/convoy/packages/detail/docker/frain-dev%252Fconvoy/0a56d59950d9ffd7988da8b0589c9cf06bf1d639619a50715d267eec1833e36b/a=amd64;xpo=linux/#versions

**Comment by Dotunj** [comment]
Hi @NanFengCheong here's the link to the docker version v0.8.0 https://cloudsmith.io/~convoy/repos/convoy/packages/detail/docker/frain-dev%252Fconvoy/78bc50fe2537ad65bdf640ee96f0ca24df8f83e3a277b19fefce5fc80b387a12/a=amd64;xpo=linux/
