### ISSUE TITLE
Verification email has no style.

### ISSUE THREAD

**Issue by Subomi** [frain-dev/convoy#1264]
The verification email does not contain any styling. See below:
![Screenshot 2023-01-10 at 10 26 08 AM](https://user-images.githubusercontent.com/5220101/211513172-0996ad6b-fc04-46cb-9b1c-f89e7834e8b2.png)

**Comment by frankMagoba** [comment]
Can I pick this up?

**Comment by Subomi** [comment]
Hey @frankMagoba, 

Thanks for trying to contribute.

We have not been able to re-create this behaviour, so I will be closing this issue.
