### ISSUE TITLE
Webhook Functions & Transformations

### ISSUE THREAD

**Issue by subomi** [frain-dev/convoy#1271]
**Problem Description**
Run arbitrary JS on webhook events.

**Comment by harshithmullapudi** [comment]
Hey @Subomi is this part of your roadmap? We would love to use convoy and also if you have some guidelines happy to contribute on this feature.

**Comment by Subomi** [comment]
Hey @harshithmullapudi, yes, this is on our roadmap. This should ship in the next quarter - Q3. But I am open to ideas on how you think this should work and what your use case would resemble.
