### ISSUE TITLE
[BUG] Improve Endpoint Column on the Events Logs Table

### ISSUE THREAD

**Issue by subomi** [frain-dev/convoy#1344]
<img width="644" alt="Screenshot 2023-02-16 at 6 57 00 PM" src="https://user-images.githubusercontent.com/5220101/219461396-a790b02f-4e76-414b-bba8-230d7609861f.png">

**Comment by haszankauna** [comment]
hello @Subomi if I'm clear on the issue, the UI needs a fix with the endpoint and time created column right?

**Comment by Subomi** [comment]
Hey @haszankauna , 

Correct. We need to implement it such that they're extending beyond their defined space.

**Comment by haszankauna** [comment]
@Subomi can you please assign the issue to me?

**Comment by Subomi** [comment]
Hey @haszankauna, sure you can go ahead. Please ping @horlah if you have any questions.
