### ISSUE TITLE
Install script doesn't work

### ISSUE THREAD

**Issue by juanstiza** [frain-dev/convoy#1396]
Launched my instance and ran this:

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/frain-dev/convoy/main/deploy/vm-deploy.sh)"
```

Got this error:

```
mkdir: cannot create directory ‘/etc/convoy’: Permission denied
```

**Comment by Subomi** [comment]
Hey @juanstiza 

You need to provide sudo access to the script. You probably provided the wrong password when it was asked. Please try it again with the correct password.

**Comment by juanstiza** [comment]
Hey @Subomi 
I did try that, and got this other error:

```
Starting containers...
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "./docker-compose.yml", line 5, column 67
```

Looks like the script fails wen trying to map this line:

```
image: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy:$VERSION
```

I then restarted the whole thing and, instead of pressing "Enter" on the version prompt, I entered "latest".

Now the installation continues.

**Comment by Subomi** [comment]
Ah, seen. If you need a specific version you specify it as `v0.8.2` etc.  I'll update the installation instructions to help with this.

**Comment by juanstiza** [comment]
Excellent, thanks!
