### ISSUE TITLE
Queue backend: Support Nats

### ISSUE THREAD

**Issue by adelowo** [frain-dev/convoy#14]
Nats is a lightweight streaming server. We need to support:

- [ ] Nats
- [ ] Nats streaming

**Comment by Just4Ease** [comment]
Add jetstream. ( you can replace nats streaming with jetstream too )

**Comment by oneEyedSunday** [comment]
Closing tickets like someone that just had breakfast delivered. 😅. Anyways
nats is on the wishlist (Just4ease)
