### ISSUE TITLE
dynamic query param support in endpoint

### ISSUE THREAD

**Issue by siprtcio** [frain-dev/convoy#1400]
Description:
We are using incoming webhook url with below configuration:

incoming webhook url
convoy.siprtc.io/ingest/1ihfJgwbeTDZNygn

endpoint url
http://tasks.apistack_cdrservice:8080/priv/Cdr/Data/

Now we are sending event like:
https://convoy.siprtc.io/ingest/1ihfJgwbeTDZNygn?uuid=c12b5bea-5c45-4431-98c7-5911ab2ce647

Our Expectation to get request url with query string on endpoint
http://tasks.apistack_cdrservice:8080/priv/Cdr/Data/?uuid=c12b5bea-5c45-4431-98c7-5911ab2ce647

but we are getting without query string
http://tasks.apistack_cdrservice:8080/priv/Cdr/Data/

Solution:
If dynamic replace variable can be supported in endpoint url then it will be great usecase

**Comment by Subomi** [comment]
Hey @siprtcio , 

This use case makes sense. Thanks for submitting the feature request. We will ship support for this soon.

**Comment by Subomi** [comment]
While you wait for this release, @siprtcio, you can use HTTP Headers to achieve this. We currently proxy down the headers to the endpoint.

**Comment by subomi** [comment]
@danvixent Please can you port this #1404  to work for this

**Comment by danvixent** [comment]
@subomi of course.

**Comment by subomi** [comment]
Hey @vavido and @siprtcio This has been released in [v23.06.1](https://github.com/frain-dev/convoy/releases/tag/v23.06.1)
