### ISSUE TITLE
State of SQS support for queue backend

### ISSUE THREAD

**Issue by sidekick-eimantas** [frain-dev/convoy#1420]
Howdy

What's the current state of SQS support for queue backend? I couldn't see anything official in the release logs
This thread https://github.com/frain-dev/convoy/issues/15 is closed indicating support is present?
Couldn't see anything re this in docs either

Thank you !

**Comment by Subomi** [comment]
Hey @sidekick-eimantas , 👋🏽 

Support for Amazon SQS was released recently in our [v0.9.0-rc.1](https://github.com/frain-dev/convoy/releases/tag/v0.9.0-rc.1) release. This still needs to ship to our cloud platform, so you will need to deploy an instance to run it. 

For documentation on how to use it, see [here](https://getconvoy.io/docs/manual/sources#message-brokers)

**Comment by Dotunj** [comment]
Hi @sidekick-eimantas, you can also join our community channel [here](https://join.slack.com/t/convoy-community/shared_invite/zt-xiuuoj0m-yPp~ylfYMCV9s038QL0IUQ) just incase you have any questions or require any assistance.

**Comment by Subomi** [comment]
Hey @sidekick-eimantas, do you need any further support here? Otherwise, we can close this issue.
