### ISSUE TITLE
[Feature Request] Add toggle for disabling endpoints

### ISSUE THREAD

**Issue by Subomi** [frain-dev/convoy#1461]
We formerly had a toggle in the project settings to decide whether a project should allow disabling events. This card is to bring that toggle back.

**Comment by uncoooloj** [comment]
Please any updates on this?

**Comment by Subomi** [comment]
Yes, this will ship in v0.9 stable release landing tomorrow.

**Comment by horlah** [comment]
Yes, closing this now. It has been merged to `main`
