### ISSUE TITLE
Queue backend: Support Amazon SQS

### ISSUE THREAD

**Issue by adelowo** [frain-dev/convoy#15]

**Comment by oneEyedSunday** [comment]
Hello Lanre, some good stuff here.

Re AWS, gokit had a PR planning for SQS support, it got tied down in reviews.
see [here](https://github.com/go-kit/kit/pull/1018) and at the last count, there are two or so competing ways of defining the interfaces.

I want to have a go at this issue, with that PR as a base.

**Comment by oneEyedSunday** [comment]
Hello Lanre, some good stuff here.

Re AWS, gokit had a PR planning for SQS support, it got tied down in reviews.
see [here](https://github.com/go-kit/kit/pull/1018) and at the last count, there are two or so competing ways of defining the interfaces.

I want to have a go at this issue, with that PR as a base.

**Comment by adelowo** [comment]
Hi @oneEyedSunday sure, happy to have you take a go at the issue. 

Namaste
