### ISSUE TITLE
[FEATURE REQUEST] RabbitMQ Support

### ISSUE THREAD

**Issue by subomi** [frain-dev/convoy#1510]
**Description**
Add support for RabbitMQ

**Comment by tttp** [comment]
our main use case would be an ingress one (AMQP) and let convoy be a reliable api caller to external REST APIs.

**Comment by tttp** [comment]
Hi @subomi, you moved the card to in progress about a year ago, is there something we can help with or test?

**Comment by subomi** [comment]
Hi @tttp, yes, this has shipped. You can pull the latest image to test it out.
