### ISSUE TITLE
[CON-85] list "Event Deliveries" with filter show empty

### ISSUE THREAD

**Issue by LomotHo** [frain-dev/convoy#1606]
### here is the "Event Deliveries" without filter
<img width="1088" alt="convoy-bug-1" src="https://github.com/frain-dev/convoy/assets/16211479/96242d15-3fd5-4023-a4fe-745529e8dca3">

### here is the "Event Deliveries" with success status filter
<img width="845" alt="image" src="https://github.com/frain-dev/convoy/assets/16211479/1846b316-1d2b-43cf-8ea1-4fb6aba3d8af">

<sub>[CON-85](https://linear.app/convoy-engineering/issue/CON-85/list-event-deliveries-with-filter-show-empty)</sub>

**Comment by debuggy** [comment]
Same issue when buiding prototype. When would this issue exepected to be solved? Thanks.

**Comment by subomi** [comment]
Hey @LomotHo and @debuggy 

A [patch](https://github.com/frain-dev/convoy/pull/1626) was merged 5 days ago. We will be releasing a new build today or tomorrow.

**Comment by subomi** [comment]
Hey @LomotHo and @debuggy this has been fixed in [v23.06.1](https://github.com/frain-dev/convoy/releases/tag/v23.06.1)
