### ISSUE TITLE
[CON-86] [BUG] Cannot add owner_id to an existing endpoint

### ISSUE THREAD

**Issue by Shulammite-Aso** [frain-dev/convoy#1613]
- Cannot update an endpoint to include owner_id
- Even when an endpoint has an owner_id from creation, the field gets stripped from it when you update the endpoint

<sub>[CON-86](https://linear.app/convoy-engineering/issue/CON-86/[bug]-cannot-add-owner-id-to-an-existing-endpoint)</sub>

**Comment by subomi** [comment]
This has been fixed in [v23.06.1](https://github.com/frain-dev/convoy/releases/tag/v23.06.1)
