### ISSUE TITLE
Implement new retry strategy - exponential backoff

### ISSUE THREAD

**Issue by subomi** [frain-dev/convoy#164]

**Comment by oneEyedSunday** [comment]
is there any where else the current default retry strategy is currently implemented / used apart from (process_event_delivery.go)?

**Comment by Subomi** [comment]
@oneEyedSunday no there isn't. But I also think this will have some major impact on the configuration layer that you'd want to look out for.

**Comment by oneEyedSunday** [comment]
yes, LoadConfig and some other places like `event.go`
