### ISSUE TITLE
[Question] Can Convoy act as a webhook proxy 

### ISSUE THREAD

**Issue by guy-frontegg** [frain-dev/convoy#1656]
Hey Guys, You are doing great job keep it up :)

I have a question if I may, Can convoy act as a webhook proxy without really setting an endpoint?

My meaning is can I send something like 
````json
{
    url: "https://acme.com",
    verb: "GET",
    headers: "x-y=z"
}
````
Thank you

**Comment by subomi** [comment]
Hey @guy-frontegg, thank you!

I am not exactly sure what the question means. Can you re-phrase it?

**Comment by guy-frontegg** [comment]
Hi @subomi ,
Thank you for answering.

What I mean is let's imagine convoy as a curl web server.
The web server gets a request to perform another web request from the given parameters.
Lets call it a dynamic endpoint

**Comment by subomi** [comment]
I see. I have two questions:

1. How will the response be generated for this use case? Will the client expect a response immediately from the upstream server, or is no response needed?
2. What HTTP verbs would be supported by the proxy?

**Comment by guy-frontegg** [comment]
I believe that the response should be as the upstream returns.
Regarding verbs, i guess it configurable.

By your questions my guess convoy does not support it out of the box :)

**Comment by subomi** [comment]
You're correct. Convoy doesn't support this use case. 

Convoy is a webhook proxy/gateway enabling you to send and receive webhooks to pre-defined endpoints and from third-party providers. From your problem description, I believe what you're describing is more of a forward proxy than a webhook proxy. Have you considered any of those technologies like [HAProxy](https://www.haproxy.org), and [Caddy](https://github.com/caddyserver/caddy)
