### ISSUE TITLE
Event delivery retry stop working after some time

### ISSUE THREAD

**Issue by achiarenza** [frain-dev/convoy#1667]
I'm experiencing a strange behaviour when a delivery attempt fails.

Convoy correctly handle the retry mechanism (exponential backoff) that is setted up for the endpoint but it seems that the job, after some retry operation, stop to work and the last scheduled attempt is never picked up. The result is a retry event with "next attempt" date time that is in the past.

<img width="1149" alt="image" src="https://github.com/frain-dev/convoy/assets/48946234/868fa767-af9a-4421-80a0-eac84b470ad8">

I'm currently using Convoy v23.06.1 but the same happened with the previous version.

**Comment by jirevwe** [comment]
Hey @achiarenza 👋🏿

Hmm, this might be a bug with the exponential backoff. I'll take a look at it.

Can you please help me with the steps to reproduce this?

**Comment by achiarenza** [comment]
Hello @jirevwe, for sure!

I'm currently using the docker compose file you provide to spin up Convoy, inside a Ubuntu 20.04.6 box.

Docker is version 23.0.5, build bc4487a.

Project settings are configured as you can see in the screenshot:
<img width="1097" alt="image" src="https://github.com/frain-dev/convoy/assets/48946234/9b17ce19-6b45-40e4-aea1-1071090d997a">

All the other configuration values are left as default.

In my tries to have the issue fixed I tried to scale up the docker worker instance to a number grater than one with `docker compose up --scale worker=2 -d` but the problem persisted.

Let me know if you need some other info.

**Comment by jirevwe** [comment]
Thanks for the info,

The exponential back-off strategy uses the values from table below which go from 10secs to 15mins. All subsequent retries after the 7th retry will be about 15 mins apart.
```Go
10000  // 10 seconds
30000  // 30 seconds
60000  // 1 minute
180000 // 3 minutes
300000 // 5 minutes
600000 // 10 minutes
900000 // 15 minutes
```

This might make a 20 retry limit strategy take about 3 hours to reach the failure state. Can you please share the worker logs, so I can debug further?

In the meantime, can you re-test it with a smaller retry limit (about 5 to 10) because I can't seem to reproduce this.

**Comment by achiarenza** [comment]
The full docker log: [worker.log](https://github.com/frain-dev/convoy/files/11769383/worker.log) with some info redacted.

**Comment by achiarenza** [comment]
The full docker log: 
[worker.log](https://github.com/frain-dev/convoy/files/11769419/worker.log)
 with some info redacted.

**Comment by achiarenza** [comment]
The full docker log: [worker.log](https://github.com/frain-dev/convoy/files/11769429/worker.log) with some info redacted.

**Comment by subomi** [comment]
Hi, @achiarenza, this has been fixed. Please feel free to re-open if you encounter any issues.
