### ISSUE TITLE
Event Query Param / Search Doesn't Work

### ISSUE THREAD

**Issue by ynouri** [frain-dev/convoy#1686]
Hi Convoy team,

I am trying to search for a specific set of incoming events. I tried to do this through the API (`/events?query=...`) and through the Events Log UI ("Search events" box). I search for a simple keyword present in the body of my incoming webhook event.

In both cases I'm seeing no events returned, while I expect some.

The API returns a 400 response with the following body:
```
{
    "status": false,
    "message": "status: 404 response: {\"message\": \"Not Found\"}"
}
```

The Events Log UI pops up a red error box with the same message (see screenshot below).

[The API documentation](https://convoy.readme.io/reference/get_v1-projects-projectid-events) is very vague about what the `query` parameter is and how it can be used. A few examples would go a long way.

Note: I'm using Convoy Cloud.

Thanks for your attention.

<img width="1920" alt="image" src="https://github.com/frain-dev/convoy/assets/1789921/444bf3f3-c6d9-4224-896a-05974aef4e45">

**Comment by ynouri** [comment]
To be clear, I'm not sure:
* if I am misusing the query param / search box (but I can't find relevant documentation)
* if I am misunderstanding the capabilities offered by this search feature (the doc mentions that the payloads are getting index though)
* or if this is an actual issue

Thank you!

**Comment by subomi** [comment]
Hey @ynouri , 

Thanks for raising this issue. Your assumptions are correct. Both the query param for the public API and the search box should search through the payload and return events that match the query string. 

We will treat this as a bug. Apologies if our response is a bit slow. We are prepping for our first [launch week](https://twitter.com/getconvoy/status/1670718132950908928) starting tomorrow. :)
