### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by briannezhad** [frain-dev/convoy#1748]
I wish this project had a Docker Image in dockerhub: https://hub.docker.com/. I can create an image but if it comes from a source its better since you can automate your update process to the idea.

**Comment by subomi** [comment]
Hey @briannezhad , 

You do not need to build from the source. We publish docker images using Cloudsmith. You can find them [here](https://cloudsmith.io/~convoy/repos/). But I recommend you try our [getting started guide](https://github.com/frain-dev/convoy#installation-getting-started), which uses the latest release.

**Comment by subomi** [comment]
Hey @briannezhad , 

Have you been able to test this out yet? Are you still experiencing any blockers here? Happy to help.
