### ISSUE TITLE
[BUG]convoy did not retry when request failed since updated to v23.9.2

### ISSUE THREAD

**Issue by LomotHo** [frain-dev/convoy#1811]
<img width="1180" alt="image" src="https://github.com/frain-dev/convoy/assets/16211479/5f5ab338-ba7a-4e32-935f-cb7b7968a7c3">

**Comment by subomi** [comment]
Hi @LomotHo, 

Please can you provide more details on how to reproduce this bug?

**Comment by LomotHo** [comment]
i deploy an additional new convoy with helm, connected to my old redis and postgresql, every failed event will not retry. i have another convoy upgrade from v23.08.x, which can reproduce this bug too.

**Comment by LomotHo** [comment]
i didn't find any related log form convoy component, how can i get it?

**Comment by jirevwe** [comment]
Hi @LomotHo, you can set the `log_level` in the values file.

**Comment by LomotHo** [comment]
> Hi @LomotHo, you can set the `log_level` in the values file.

let me have a try

**Comment by jirevwe** [comment]
I've been able to repro this. Seems like we introduced a bug in the last release which has been fixed on main.

**Comment by jirevwe** [comment]
Hey @LomotHo this has been fixed in the [latest release](https://github.com/frain-dev/convoy/releases/tag/v23.10.1). All you need to do is to change the image tag to `v23.10.1`
