### ISSUE TITLE
Unable to send an event

### ISSUE THREAD

**Issue by mermetbt** [frain-dev/convoy#1825]
Hello,

I tested the app in a Kubernetes environment, succeed to run the dashboard properly.

First of all, the app is really really slow due to the polling done that stacks the requests `https://convoy/ui/organisations/01HDZEGWZFSHM2RHSMY0SXKRB2/projects/01HDZHA1KSGP2GHYJTXTPSFGJT/eventdeliveries`.

Second, I configured one project and got this `/ingest/4KBhmcsGNyWdpKpy`, I'm unable to know how to use this as an URL.
![Screenshot_20231030_135336](https://github.com/frain-dev/convoy/assets/711667/b7d2ed1a-3499-486a-920b-ddd2884f2046)

I tried prefixing my base URL with it like this `https://convoy/ingest/4KBhmcsGNyWdpKpy` but this is not working

```
{"status":false,"message":"Provider type undefined"}
```

The [documentation](https://getconvoy.io/docs/getting-started/sending-webhook-example) is not updated, and tells to execute something like this to send an event:

```
https://dashboard.getconvoy.io/api/v1/projects/<project-id>/events
```

None of the format provided by the doc, or by the app is supposed to work... It's really frustrating.

Regards,

**Comment by subomi** [comment]
Hey @mermetbt, 

Sorry for the frustrating experience. The approach to prefix the ingest path with your Base URL is the correct approach. But it seems there's a bug with how your source is configured; that's what you're getting: 

```json
{"status":false,"message":"Provider type undefined"}
```

Please can you share details of your source configuration?

**Comment by mermetbt** [comment]
No idea what you are talking about. I use the default configuration, the only things that differ is the nginx ingress configuration that is already working.

**Comment by mermetbt** [comment]
Thanks for your reply, I will try that.

1. Does the `server.env.host` should contains the `https://` prefix?
2. Ok thanks, that might explain why.
