### ISSUE TITLE
URL and Name should not be required fields in the UpdateEndpoint model

### ISSUE THREAD

**Issue by yehuda-margolis** [frain-dev/convoy#1826]
https://github.com/frain-dev/convoy/blame/e87edff6fec9b484eda440d3d7d56eeabae24c1e/api/models/endpoint.go#L36C2-L36C2

**Comment by subomi** [comment]
Hey @yehuda-margolis, the APIs don't currently support `PATCH` requests, so to update a resource, you'd need to supply all the parameters.
