### ISSUE TITLE
Logging is to big

### ISSUE THREAD

**Issue by mermetbt** [frain-dev/convoy#1828]
Hello,

I've check the logs and discovered huge quantity of unreadable bytes, after investigation it seems to be the images and assets used by the app that are logged via the requests made to the API. This create huge log files and slow down all the logging systems for nothing.

Is there a way to disable the logging of the assets?

Thanks.

**Comment by jirevwe** [comment]
Hmm, this is a bug, I'll release a new chart in about an hour. It should not log that much anymore.

**Comment by mermetbt** [comment]
Thanks!

**Comment by jirevwe** [comment]
I've released this. Apologies for the delay. The version number is 1.0.8.

Also, for better realtime communication, you can consider joining our [community slack](https://join.slack.com/t/convoy-community/shared_invite/zt-23lte3yx0-zPhmwzB41Rd__tMe0Xhdrg).

**Comment by mermetbt** [comment]
Thanks for your reactivity! I will try that right away!
