### ISSUE TITLE
[CON-230] The Source and End Point combo box in Subscriptions is limited to one page.

### ISSUE THREAD

**Issue by ValkoDagon** [frain-dev/convoy#1848]
When your convoy project has a lot of sources and end points (my project has 96 so far) it becomes impossible to create new subscriptions with sources and end points that are beyond the most recent 20.

Please improve the drop down selections inside the create subscription page to allow for all sources and end points to be selected from the list.

<sub>[CON-230](https://linear.app/convoy-engineering/issue/CON-230/the-source-and-end-point-combo-box-in-subscriptions-is-limited-to-one)</sub>

**Comment by jirevwe** [comment]
Hey @ValkoDagon,

Thanks for raising this. It's in our backlog, we'll link to this issue when we open a PR for it.
