### ISSUE TITLE
[BUG] Pending invites are not correctly deleted

### ISSUE THREAD

**Issue by itek09** [frain-dev/convoy#1858]
## Situation:
I created an invite for an user that was not accepted. If you remove the invitation while it is pending, you cannot create it again after remove it.

The invitation disappear from the UI but if you try to create it for the same email, it gives you the "An Invite For This Email Already Exists" error.

## How to replicate:
Create an invitation for an email address
Remove the invite
Try to create an invite for the same email address

## Information:
Convoy deployed using Helm Chart 2.0.0

**Comment by danvixent** [comment]
Hi @itek09 thank you for filing this bug, #1860 fixes this.
