### ISSUE TITLE
Unknown command "scheduler"

### ISSUE THREAD

**Issue by nabeelio** [frain-dev/convoy#1863]
Hi,

I'm interested in Convoy, trying out the Docker Compose setup locally first, I'm seeing this in the logs:

```
local-scheduler-1  | time="2024-01-09T18:51:19Z" level=fatal msg="unknown command \"scheduler\" for \"Convoy\""
local-scheduler-1  | Error: unknown command "scheduler" for "Convoy"
local-scheduler-1  | Run 'Convoy --help' for usage.
local-scheduler-1  | Error: unknown command "scheduler" for "Convoy"
local-scheduler-1  | Run 'Convoy --help' for usage.
```

I've checked out both the latest release and the current main (v23.11.1)

**Comment by subomi** [comment]
Hi @nabeelio , you're using the wrong docker-compose file. Please use the instructions [here](https://github.com/frain-dev/convoy/tree/main?tab=readme-ov-file#installation-getting-started).

**Comment by nabeelio** [comment]
Hi @subomi, that's the one I'm using/the instructions I'm following

**Comment by subomi** [comment]
@nabeelio I just tried it again, and it worked. Try starting afresh. Delete the repository and start again. Ensure you're on the `main` branch.

**Comment by nabeelio** [comment]
Very strange, it's working now. I've sent an email into sales. Thanks for the help!

**Comment by subomi** [comment]
@nabeelio Very Cool. I didn't receive your email yet. If you're interested in the Cloud, you can sign up here -- [cloud.getconvoy.io](https://cloud.getconvoy.io).

**Comment by nabeelio** [comment]
I used the form under Self-Hosted -> Enterprise

**Comment by subomi** [comment]
Got it. I'll check and respond!

**Comment by nabeelio** [comment]
Send, thanks!
