### ISSUE TITLE
[Feature request] Allow filtering on list portal links endpoint

### ISSUE THREAD

**Issue by rishavmukherji** [frain-dev/convoy#1868]
## Title
   Allow filtering on [portal links endpoint](https://convoy.readme.io/reference/get_v1-projects-projectid-portal-links)

## To-do
[ ] Add a filter query param to this [endpoint](https://convoy.readme.io/reference/get_v1-projects-projectid-portal-links). Would make it easier to fetch portal links based on `owner_id`

**Comment by subomi** [comment]
This has been fixed in the latest release! 🎉
