### ISSUE TITLE
[Bug report]: HTTP GET ingest error "Provider type undefined"

### ISSUE THREAD

**Issue by Aareksio** [frain-dev/convoy#1912]
### Description
```
curl localhost:5005/ingest/1PCxjUA7xNCGvV2X
{"status":false,"message":"Provider type undefined"}
```

### Reproduction
1. Follow [installation guide](https://getconvoy.io/docs/deploy/install-convoy)
```sh
git clone https://github.com/frain-dev/convoy.git
cd convoy
docker compose -f configs/local/docker-compose.yml up
```

2. Visit web interface, log in with default credentials:
```
Username: superuser@default.com
Password: default
```

3. Go through onboarding (create Organization, Project, Source, Endpoint)
<img width="813" alt="Screenshot 2024-02-04 at 18 52 13" src="https://github.com/frain-dev/convoy/assets/11166786/0053a916-b6e9-40ff-999c-59926b827d3b">

5. Copy obtained Ingest URL for the Source
6. Execute CURL to copied URL
```sh
curl localhost:5005/ingest/1PCxjUA7xNCGvV2X
{"status":false,"message":"Provider type undefined"}
```

### Expected behavior
```
{"status":true,"message":"Event received"}
```

### Stack (please complete the following information):

Ref: https://github.com/frain-dev/convoy/blob/main/configs/local/docker-compose.yml

 - Convoy: v24.1.2
 - PostgreSQL: 15.2-alpine
 - Redis: alpine (7.2.1)
 - OS: MacOS 14.3
 - Browser: curl

### Additional context
```
psql -U convoy -W -d convoy
\x
SELECT * FROM sources;

-[ RECORD 1 ]----------------+-----------------------------------------------------------------------
id                           | 01HNSGMNN4QNMM2TPXF13KK7PK
name                         | Test
type                         | http
mask_id                      | 1PCxjUA7xNCGvV2X
provider                     | 
is_disabled                  | f
forward_headers              | 
project_id                   | 01HNSG3XBEY8TK004VQ0KVZ852
source_verifier_id           | 01HNSGMNNDBFK41R75QCMBBA8N
pub_sub                      | {"sqs": null, "type": "", "kafka": null, "google": null, "workers": 0}
created_at                   | 2024-02-04 07:34:33.901343+00
updated_at                   | 2024-02-04 07:34:33.901343+00
deleted_at                   | 
custom_response_body         | 
custom_response_content_type | 
idempotency_keys             | 
```

Only place where this error can be triggered is here: https://github.com/frain-dev/convoy/blob/main/api/ingest.go#L72

**Comment by subomi** [comment]
Hey, @Aareksio, that's a wrong error type we should fix. It's happening because you're making a `GET` request instead of a `POST` request.

**Comment by subomi** [comment]
Please feel free to re-open if you have another question. @Aareksio
