### ISSUE TITLE
[Feature request]: Improve migrations with a list subcommand

### ISSUE THREAD

**Issue by subomi** [frain-dev/convoy#1919]
### Is your feature request related to a problem? Please describe.
Migrating up/down today is a pain. It is not clear which migrations are to be attributed with which version, so users have to manually compare the `gorp_migrations` table with the `sql/` directory of the release tag. 

### Describe the solution you'd like
We should create a `convoy migrate list` that outputs all the migrations with their respective convoy version.

**Comment by Ayo-Awe** [comment]
@subomi I'd like to work on this issue
