### ISSUE TITLE
[Feature request]: Implement circuit breakers to manage endpoint failure

### ISSUE THREAD

**Issue by subomi** [frain-dev/convoy#1926]
### Is your feature request related to a problem? Please describe.
We currently don't have a good solution to manage consistent endpoint failure. If an endpoint fails today, it'll continue to clog the queue, affecting other available endpoints.

### Describe the solution you'd like
Implement the circuit breaker algorithm to prevent sending events to failing endpoints.

**Comment by olamilekan000** [comment]
Hi, can you give more context on how this can be reproduced?
