### ISSUE TITLE
[Bug report]: Rate Limit Not Taking Effect

### ISSUE THREAD

**Issue by jgngo** [frain-dev/convoy#1927]
### Describe the bug
Setting a rate limit on the endpoint does not take effect

### To Reproduce
1. Create an incoming webhooks project
2. Create a source
3. Create an endpoint and set the rate limit to Duration: 60 seconds and Limit: 1
4. Create a subscription for the source to the endpoint
5. Send message to the incoming webhook 5 times in succession
6. In Event Deliveries, you will see the 5 API calls succeed

### Expected behavior
In Event Deliveries, only 1 should succeed and the other 4 should be scheduled given that the rate limit is only 1 for every 60 seconds.

### Stack (please complete the following information):
 - Convoy: v24.1.2

**Comment by jirevwe** [comment]
Hey @jgngo,

We'll look into this.

**Comment by jirevwe** [comment]
Hey @jgngo, this has been fixed and merged.
