### ISSUE TITLE
[Bug report]: Project type selection is broken in v24.1.2

### ISSUE THREAD

**Issue by duuri-mollinen** [frain-dev/convoy#1934]
### To Reproduce
1. Start new instance with docker compose
2. Create organisation
3. Attempt to create project
4. Project type radio buttons are not accepting selections

### Expected behavior
User is able to select either incoming or outgoing web hook type

### Screenshots
<img width="862" alt="image" src="https://github.com/frain-dev/convoy/assets/87829866/2de2a88d-fdef-4859-b5aa-f958d33eb8fa">

### Stack (please complete the following information):
version: "3"

services:
    web:
        image: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy:v24.1.2
        command: ["/start.sh"]
        volumes:
            - ./convoy.json:/convoy.json
        restart: on-failure
        ports:
            - "5005:5005"
        healthcheck:
            test: ["CMD-SHELL", "wget -q --spider localhost:5005/health"]
            interval: 5s
            timeout: 15s
            retries: 3
            start_period: 5s
        depends_on:
            - postgres
            - redis_server

    worker:
        image: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy:v24.1.2
        command: ["./cmd", "worker", "--config", "convoy.json"]
        volumes:
            - ./convoy.json:/convoy.json
        restart: on-failure
        depends_on:
            web:
                condition: service_healthy

    stream:
        image: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy:v24.1.2
        command: ["./cmd", "stream", "--config", "convoy.json"]
        volumes:
            - ./convoy.json:/convoy.json
        restart: on-failure
        depends_on:
            web:
                condition: service_healthy

    ingest:
        image: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy:v24.1.2
        command: ["./cmd", "ingest", "--config", "convoy.json"]
        volumes:
            - ./convoy.json:/convoy.json
        restart: on-failure
        depends_on:
            web:
                condition: service_healthy

    postgres:
        image: postgres:15.2-alpine
        restart: unless-stopped
        environment:
            POSTGRES_DB: convoy
            POSTGRES_USER: convoy
            POSTGRES_PASSWORD: convoy
            PGDATA: /data/postgres
        volumes:
          - postgres_data:/data/postgres

    redis_server:
        image: redis:alpine
        restart: always
        volumes:
          - redis_data:/data

volumes:
    postgres_data:
    redis_data:

### Additional context
Please feel free to add any other context about the problem here.

**Comment by subomi** [comment]
Hey @duuri-mollinen, can you try out [24.1.4](https://github.com/frain-dev/convoy/releases/tag/v24.1.4) and see if this issue persists?

**Comment by duuri-mollinen** [comment]
> Hey @duuri-mollinen, can you try out [24.1.4](https://github.com/frain-dev/convoy/releases/tag/v24.1.4) and see if this issue persists?

Hi, a click to the box that describes the Incoming or outgoing web hook changes the type, but click to the radio button in either of those boxes still does nothing

**Comment by Oluwadaminiola** [comment]
Hi @duuri-mollinen, we will make a fix for this and notify you once this is done

**Comment by Oluwadaminiola** [comment]
> Hi @duuri-mollinen, we will make a fix for this and notify you once this is done

@duuri-mollinen this has been resolved

**Comment by Oluwadaminiola** [comment]
> Hi @duuri-mollinen, we will make a fix for this and notify you once this is done

@duuri-mollinen this has been resolved
