### ISSUE TITLE
Not able to Store data in pstgres database.

### ISSUE THREAD

**Issue by tejaswinit2024** [frain-dev/convoy#1941]
I have install the latest version of Convoy v24.1.2 but still i am not able to store the data in the postgres database as I have added the database connection details in convoy file and configured not able to store data. Is their any procedure need to follow please mention.

**Comment by jirevwe** [comment]
You can use [this guide](https://docs.getconvoy.io/deployment/configuration) to create the config file.

**Comment by tejaswinit2024** [comment]
2024-02-23 17:15:52 2024-02-23 11:45:52.459 UTC [1] LOG:  starting PostgreSQL 15.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
2024-02-23 17:15:52 2024-02-23 11:45:52.459 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-02-23 17:15:52 2024-02-23 11:45:52.459 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-02-23 17:15:52 2024-02-23 11:45:52.463 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-02-23 17:15:52 2024-02-23 11:45:52.469 UTC [24] LOG:  database system was shut down at 2024-02-23 11:45:19 UTC
2024-02-23 17:15:52 2024-02-23 11:45:52.475 UTC [1] LOG:  database system is ready to accept connections
2024-02-23 17:15:52
2024-02-23 17:15:52 PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-02-23 17:15:52
 these are the logs i am getting when i config the convoy..

Thanks,
Tejaswini
________________________________

**Comment by jirevwe** [comment]
Hmm, These are postgres logs, what am I meant to do with them? Can I see your convoy.json file?

**Comment by tejaswinit2024** [comment]
This is my convoy.json file. Here i have configured the Db connection but still i am not able to store the data in database.

Thanks,
Tejaswini
________________________________

**Comment by tejaswinit2024** [comment]
convoy.json file
{
  "auth": {
    "native": {
      "enabled": true
    },
    "jwt": {
      "enabled": true,
      "secret": "<insert-jwt-secret>",
      "expiry": 3600,
      "refresh_secret": "<insert-jwt-refresh-secret>",
      "refresh_expiry": 86400
    },
    "is_signup_enabled": true
  },
  "database": {
    "type": "postgres",
    "scheme": "postgres",
    "host": "localhost",
    "username": "postgres",
    "password": "postgres",
    "database": "convoy",
    "options": "sslmode=disable",
    "port": 5432,
    "max_open_conn": 100,
    "max_idle_conn": 10,
    "conn_max_lifetime": 3600
  },
  "redis": {
    "scheme": "redis",
    "host": "localhost",
    "username": "redis",
    "password": "redis",
    "database": "0",
    "port": 6379,
    "addresses": ""
  },
  "prometheus": {
    "dsn": "<insert-prometheus-dsn>"
  },
  "server": {
    "http": {
      "ssl": true,
      "ssl_cert_file": "<insert-ssl-cert-file>",
      "ssl_key_file": "<insert-ssl-key-file>",
      "port": 5005,
      "ingest_port": 5006,
      "worker_port": 5007,
      "socket_port": 5008,
      "domain_port": 5009,
      "proxy": ""
    }
  },
  "max_response_size": 102400,
  "smtp": {
    "ssl": true,
    "provider": "<insert-smtp-provider>",
    "url": "<insert-smtp-url>",
    "port": 587,
    "username": "<insert-smtp-username>",
    "password": "<insert-smtp-password>",
    "from": "<insert-smtp-from>",
    "reply-to": "<insert-smtp-reply-to>"
  },
  "env": "production",
  "logger": {
    "level": "info"
  },
  "tracer": {
    "type": "new_relic",
    "new_relic": {
      "app_name": "<insert-new-relic-app-name>",
      "license_key": "<insert-new-relic-license-key>",
      "config_enabled": true,
      "distributed_tracer_enabled": true
    }
  },
  "host": "<insert-host>",
  "custom_domain_suffix": "<insert-custom-domain-suffix>",
  "feature_flag": "experimental",
  "analytics": {
    "enabled": true
  },
  "storage_policy": {
    "type": "s3 | on_prem",
    "s3": {
      "prefix": "<insert-s3-prefix>",
      "bucket": "<insert-s3-bucket>",
      "access_key": "<insert-s3-access-key>",
      "secret_key": "<insert-s3-secret-key>",
      "region": "<insert-s3-region>",
      "session_token": "<insert-s3-session-token>",
      "endpoint": "<insert-s3-endpoint>"
    },
    "on_prem": {
      "path": "<insert-on-prem-path>"
    }
  },
  "consumer_pool_size": 200
}
________________________________
