### ISSUE TITLE
[Bug report]: I cannot access the user settings page without creating an organisation

### ISSUE THREAD

**Issue by subomi** [frain-dev/convoy#1967]
### Describe the bug
On a fresh installation, I cannot access the user settings page without creating an organisation.

### To Reproduce
1. Spin up a fresh installation
2. Login with the default user -- `superuser@default.com`
3. Try to access the `my account` tab under the user dropdown top right.

### Expected behavior
It should open the user settings page instead nothing happens.

**Comment by BolajiOlajide** [comment]
The [logic for this is a bit complicated as the router doesn't get mounted when there are no organisations](https://sourcegraph.com/github.com/frain-dev/convoy/-/blob/web/ui/dashboard/src/app/private/private.component.html?L100). A much larger conversation should be had around why and if that logic should still remain.

However, a simple workaround can be done by checking if the router URL is `/user-settings`.
