### ISSUE TITLE
[Bug report]: Endpoint not displaying on Event deliveries table

### ISSUE THREAD

**Issue by tobby** [frain-dev/convoy#2067]
### Describe the bug

Endpoint is not displaying on the event deliveries table on the event deliveries page

### To Reproduce

1. Go to event deliveries
2. Scroll down to see the event deliveries table
3. See error

### Expected behavior

Endpoints should be included in the table data

### Screenshots

![image](https://uploads.linear.app/314fcfc4-ac20-49b2-bc85-caa9ac793c1c/f8e89bdb-8936-4bd2-8183-c4ae237d10c9/4c864550-d5bf-442e-8c6d-85a50191f2ec?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMxNGZjZmM0LWFjMjAtNDliMi1iYzg1LWNhYTlhYzc5M2MxYy9mOGU4OWJkYi04OTM2LTRiZDItODE4My1jNGFlMjM3ZDEwYzkvNGM4NjQ1NTAtZDViZi00NDJlLThjNmQtODVhNTAxOTFmMmVjIiwiaWF0IjoxNzE4Mjc2MzU5LCJleHAiOjMzMjg4ODM2MzU5fQ.hv3tTsMtgfobyuImzLFAMWzCb7Zg3X1wvkcU8tGYqSc)

### Stack (please complete the following information):

* Convoy: \[e.g. v24.5.1\]
* Browser \[e.g. chrome\]

**Comment by Oluwadaminiola** [comment]
@tobby thank you for reporting this, please can you help check if your `endpoint_metadata` is being returned under your event delivery object
