### ISSUE TITLE
Rate Limiting per Group.

### ISSUE THREAD

**Issue by Subomi** [frain-dev/convoy#207]
In a multi-tenant model, allow us config rate limiting per group.

**Comment by oneEyedSunday** [comment]
Hello @Subomi  what does `group` mean in this scenario?


does this mean, given access to a group resource (r.Route("/groups",), we want to rate limit access to that resource?

**Comment by Subomi** [comment]
Hey man, @oneEyedSunday 

So a group represents a project in an organisation e.g. Helicarrier have two APIs that require webhooks: sendcash-pay & buycoins-api these two are groups. 

The goal of rate limiting is to rate limit per group. E.g. sendcash-pay can only send 5k/minute while buycoins-api can send 15k/minute. This is necessary for resource allocation among groups. For this to work, we need to create a rate limiting configuration for each group and track their usage against that value.

For a distributed rate limiter, I think this is aside it and should require a different issue on it's own.

**Comment by oneEyedSunday** [comment]
What route groups are directly impacted here?

Looks like:
- eventRouter.With(instrumentPath("/events")).Post("/", app.CreateAppEvent)
- r.Route("/eventdeliveries", func(eventDeliveryRouter chi.Router) {

**Comment by Subomi** [comment]
Yeah, the first one - `CreateAppEvent`

**Comment by oyekanmiayo** [comment]
Hi, is this issue achieved with https://github.com/frain-dev/convoy/pull/229?

(I really like the convoy project, and I'm interested in contributing, so I'm just going through open issues to see where to start.)

**Comment by danvixent** [comment]
I think it has been achieved @oyekanmiayo.
cc @Subomi @jirevwe

**Comment by danvixent** [comment]
Then we can close this.
