### ISSUE TITLE
[Bug report]: Webhooks not seeing in Dashboard

### ISSUE THREAD

**Issue by Xtreme89** [frain-dev/convoy#2074]
### Describe the bug
When i sent a Webhook to my Server running with convoy, i dont see the event in the dashboard. I got a http response 200 back to my python script and i also see in the tcpdump that the message is reaching my server and my server is answer
so what is the reason why i dont see the event in the dashboard?

**GUI saying "You have no incoming events."**

Software is running on docker with this guide: https://docs.getconvoy.io/deployment/install-convoy/docker

 - Convoy:Convoy v24.5.1
 - OS: Ubuntu 22.04.4 LTS
 - Docker: Docker version 26.1.4, build 5650f9b

```
POST /ingest/IyfVnxGqtjjQcDdJ HTTP/1.1
Host: xxxxxxx:5005
User-Agent: python-requests/2.31.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Length: 43
Content-Type: application/json

{"content": "Dies ist eine Testnachricht."}
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
X-Request-Id: 19a860f0bda9/CyNJQ6afqA-000031
Date: Fri, 21 Jun 2024 18:09:08 GMT
Content-Length: 53

{"status":true,"message":"Event received","data":43}
```

**Comment by subomi** [comment]
Hey @Xtreme89, 

Here are a few steps to you can take to debug this:
1. Confirm it's showing up in the `Events Log`. If it's showing up here but not on the `Event Delivery` page, it's likely a subscription configuration problem. 
2. If it's not showing up at all, check the `/queue/monitoring/` page and check the `CreateEventQueue` -- it will show you the reason why it failed to ingest.

**Comment by Xtreme89** [comment]
HI,

thanks for your help

On booh pages Event Log and Event Delivery there is nothing.

How i can check this:

`If it's not showing up at all, check the /queue/monitoring/ page and check the CreateEventQueue -- it will show you the reason why it failed to ingest.`

**Comment by subomi** [comment]
You can try retrying it from there to check for the error message (if any)

**Comment by Xtreme89** [comment]
There is no Button like retrying or something like that, just archiv and delete

**Comment by subomi** [comment]
Can you confirm that the `worker` container is running?

**Comment by Xtreme89** [comment]
the following docker container are running
local-web-1
local-pgbouncer-1
local-redis_server-1
local-postgres-1

**Comment by subomi** [comment]
There should be a worker component running as well.

**Comment by Xtreme89** [comment]
OK i see,

container ingest and worker dont come up.

i think it is because of this issue https://github.com/frain-dev/convoy/issues/2068

when web not started correctly the other container dont came up maybe?

**Comment by subomi** [comment]
Yes, that is correct. The way it is currently organised might not be the best approach, but they all start in a crash loop till they eventually become healthy.

**Comment by Xtreme89** [comment]
when i do "docker-compose restart" the ingest and worker came up and it is working messages is showing in the gui


maybe you can look for a solution?

**Comment by subomi** [comment]
I would love to find a solution; if you're interested, I'll accept pull requests.

**Comment by Xtreme89** [comment]
One addiontal question
i have added in the convoy.json
https for web server

    "server": {
        "http": {
            "ssl": true,
            "ssl_cert_file": "cert.pem",
            "ssl_key_file": "key.pem",
            "port": 5005


it is also working i can access the gui, but now ingest container is unhealty after reboot

have i forgot something?

**Comment by subomi** [comment]
Can you share the logs?

**Comment by Xtreme89** [comment]
That is my problem ingest container dont have any logs when i look into it

**Comment by Xtreme89** [comment]
my fault web is not starting correctly

**Comment by Xtreme89** [comment]
ok my fault, everything is working
