### ISSUE TITLE
[Bug report]: "Provider type undefined"

### ISSUE THREAD

**Issue by chrischerrett** [frain-dev/convoy#2080]
### Describe the bug
When I attempt to call an incoming webhook, I get the message:

`{
"status": false,
"message": "Provider type undefined"
}`

### To Reproduce
1. Create a Source with 'None' for Source Veritication
2. Create Endpoint
3. Create Subscription

### Expected behavior
Expect webhook to run. However, I get this error. Database also showing '' in Source Provider column. Is this expected?

### Screenshots
<img width="709" alt="Screenshot 2024-06-28 at 11 40 33" src="https://github.com/frain-dev/convoy/assets/50097558/a87a961d-9d09-4e37-988f-d5780bcedb5b">

### Stack (please complete the following information):
 - Docker: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy:v24.5.1

**Comment by subomi** [comment]
Hi @chrischerrett, 

The problem here is you're making a `GET` request instead of a `POST` request to the ingest URL.

**Comment by chrischerrett** [comment]
Of course! Thank you @subomi
