### ISSUE TITLE
[Bug Report]: Deleted org members cannot be reinvited to an org

### ISSUE THREAD

**Issue by BolajiOlajide** [frain-dev/convoy#2096]
### To Reproduce

- a user’s invite has been accepted
- their org member has been deleted
- the user account is not deleted
We won’t be able to re-invite the user again.

### Expected behavior

 if the invite and org member are both deleted and the user isn't deleted I should able to reinvite the user to the same org again

### Screenshots
If applicable, could you add screenshots to help explain your problem?

### Stack (please complete the following information):
 - Convoy: [e.g. v23.10.1]
 - PostgreSQL: [e.g. 15]
 - Redis: [e.g. 7.2]
 - OS: [e.g. Ubuntu 20.04.6 LTS]

### Additional context
Please feel free to add any other context about the problem here.

**Comment by BolajiOlajide** [comment]
Okay, this one is quite tricky for a couple of reasons. The bug is caused by a valid database constraint.

![CleanShot 2024-07-22 at 23 06 09@2x](https://github.com/user-attachments/assets/ad4ef612-6a65-4333-9c77-219c233bde79)

The `organisation_invites_invitee_email` constraint ensures we have invite per user for any given organization, however, this constraint doesn't take into consideration the status of the invite whether it has been `accepted` or otherwise.

My recommendation is to have this constraint removed, then have the check done in code where we just check if there's a record for `organisation_members` for that user that isn't deleted.

cc @jirevwe

**Comment by jirevwe** [comment]
Hmm, alright.
