### ISSUE TITLE
Endpoint Authentication Not Visibile

### ISSUE THREAD

**Issue by StreamlinedStartup** [frain-dev/convoy#2121]
### Describe the bug
No endpoint authentication options are available using `convoy:v24.6.4`
### To Reproduce

- Create or edit endpoint

### Expected behavior
Have options for adding endpoint authentication as outlined in docs here - https://docs.getconvoy.io/product-manual/endpoints

### Screenshots
![CleanShot 2024-08-18 at 08 57 03](https://github.com/user-attachments/assets/d80acbae-c64f-4af7-9709-cacdcf7cbd56)

### Stack (please complete the following information):
 - Convoy: v24.6.4
 - PostgreSQL: bitnami/postgresql:latest
 - Browser Chrome

### Additional context
Not sure if i'm missing something or what - apologies if I overlooked it.

**Comment by brentshulman-silkline** [comment]
I wanted to test your product, but now I can't. Completely blocked on this

**Comment by Oluwadaminiola** [comment]
@brentshulman-silkline this has been resolved now, please pull and try again

**Comment by Oluwadaminiola** [comment]
@brentshulman-silkline @StreamlinedStartup Also, please pull the new image on Docker hub as you can't pull the old image on Cloudsmith anymore

**Comment by subomi** [comment]
@brentshulman-silkline, I think you deployed a Cloud instance. We'll push this patch to your cluster so that you can continue testing.

**Comment by brentshulman-silkline** [comment]
Still not seeing 24.8.1

**Comment by subomi** [comment]
@brentshulman-silkline should be up now; sorry for the delay.
