### ISSUE TITLE
[Bug report]: Error 402 - payment required when attempting to pull convoy image

### ISSUE THREAD

**Issue by FredericEgmorte** [frain-dev/convoy#2143]
### Description
Convoy has been deployed on EKS kubernetes cluster till few months and this morning the pod tried to restart. But the pod failed to pull image with an error 402: payment required.
Even locally, it's not possible to pull this image

### To Reproduce
Deploy the helm chart of convoy

### Expected behavior
Deployment up and running

### Logs
Kubectl describe of pods:
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  8m10s                  default-scheduler  Successfully assigned convoy/convoy-migrate-l8s5g to <ip>
  Normal   Pulling    6m43s (x4 over 8m10s)  kubelet            Pulling image "docker.cloudsmith.io/convoy/convoy/frain-dev/convoy:v24.1.2"
  Warning  Failed     6m42s (x4 over 8m8s)   kubelet            Failed to pull image "docker.cloudsmith.io/convoy/convoy/frain-dev/convoy:v24.1.2": failed to pull and unpack image "docker.cloudsmith.io/convoy/convoy/frain-dev/convoy:v24.1.2": failed to copy: httpReadSeeker: failed open: unexpected status code https://docker.cloudsmith.io/v2/convoy/convoy/frain-dev/convoy/blobs/sha256:e22229b9aeb8bd56b7ec329ca5c1cbe0368d0f5e6a45e2bad7ba667fc56a2ac6: 402 Payment Required
  Warning  Failed     6m42s (x4 over 8m8s)   kubelet            Error: ErrImagePull
  Warning  Failed     6m28s (x6 over 8m8s)   kubelet            Error: ImagePullBackOff
  Normal   BackOff    3m4s (x21 over 8m8s)   kubelet            Back-off pulling image "docker.cloudsmith.io/convoy/convoy/frain-dev/convoy:v24.1.2"

### Stack (please complete the following information):
 - Convoy: v24.1.2
 - PostgreSQL: 15

**Comment by jirevwe** [comment]
Apologies for the inconvenience. Our Cloudsmith bandwidth is depleted. We recently moved our images to [DockerHub](https://hub.docker.com/r/getconvoy/convoy), but you will need to upgrade to `v24.8.1`. Please make sure to read the [release notes](https://docs.getconvoy.io/release-notes/releases#breaking-changes) before upgrading.

**Comment by FredericEgmorte** [comment]
Thanks ! I have just tested on docker hub and finally succeded to pull the image. Thank you for your quick reply @jirevwe

**Comment by subomi** [comment]
@FredericEgmorte Don't forget to give us a star. :)
