### ISSUE TITLE
Cannot change the encoding for calculating signature for outgoing event

### ISSUE THREAD

**Issue by sevensinjai** [frain-dev/convoy#2200]
when an event is sent from convoy to an endpoint, there will be a `x-convoy-signature`. This signature is calculated using `hex` encoding, I want to change it to `base64`, how do i do it? 

I cannot find it in both endpoint setting and project setting page.

**Comment by jirevwe** [comment]
Hey @sevensinjai,

You can configure this from the "Project Signature History" tab on the project settings page.
<img width="1044" alt="Screenshot 2024-12-06 at 14 22 16" src="https://github.com/user-attachments/assets/1f1c5ff8-ec44-4761-88e5-e2a2476234fc">

**Comment by jirevwe** [comment]
Hey, @sevensinjai, I'll close this issue. Please feel free to open a new one if you encounter this again.
