### ISSUE TITLE
Multiple status filter for event deliveries

### ISSUE THREAD

**Issue by horlah** [frain-dev/convoy#236]
UI should be able to filter event deliveries by multiple statuses at once instead of one by one

**Comment by oneEyedSunday** [comment]
I think this is already a thing.


```go
type EventDeliveryRepository interface {
LoadEventDeliveriesPaged(context.Context, string, string, string, EventDeliveryStatus, models.SearchParams, models.Pageable) ([]EventDelivery, pager.PaginationData, error)
}
```


```go
func (db *eventDeliveryRepo) LoadEventDeliveriesPaged(ctx context.Context, groupID, appID, eventID string, status convoy.EventDeliveryStatus, searchParams models.SearchParams, pageable models.Pageable) ([]convoy.EventDelivery, pager.PaginationData, error) {}
```

or do you mean multiple EventDeliveryStatus'es?

**Comment by oneEyedSunday** [comment]
cc @Subomi

**Comment by Subomi** [comment]
What we have will filter by one status at once. This issue is about filtering for a list of statuses at once. Essentially `[]EventDeliveryStatus` @oneEyedSunday

**Comment by oneEyedSunday** [comment]
oh ok. This clears it up

**Comment by Subomi** [comment]
@horlah This API works already, but the UI doesn't. The UI doesn't enable us select multiple status at once.
