### ISSUE TITLE
Implement search apps

### ISSUE THREAD

**Issue by Subomi** [frain-dev/convoy#281]
We need to be able to search app names. This is useful for 
1. Search through Lots of the apps. 
2. Filtering by apps.

**Comment by jirevwe** [comment]
Picking this up too. To clarify:
- who can search through apps? will any auth be done before filtering?
- are searches bound be group scopes or is the search general
- if a super user is search should the group scopes be ignored?

**Comment by Subomi** [comment]
- Anyone who has access to the UI. Auth will be done if the instance is configured to require auth.
- Yes, search is bounded by group scopes.
- No, no difference. It is bounded by group scopes. 

The feature is for operators running convoy. They can login to the dashboard, check a specific group, see all their apps and filter through them. Also: The API here will be also used for autocomplete filters.
