### ISSUE TITLE
Update convoy CLI interface.

### ISSUE THREAD

**Issue by Subomi** [frain-dev/convoy#282]
- [x] Show version number.
- [ ] Enable `convoy server` support all config values. E.g. `convoy server --queue <redis-dsn> --db <mongodb-dsn>`

Notes
- The CLI parameters should override config file parameters.

**Comment by jirevwe** [comment]
Can I pick this up? Where should we show the version number?

**Comment by Subomi** [comment]
@jirevwe Yes, but you already did the version number in your last pr, correct? 

Also, there are other things that should be here. Let me update it.

**Comment by jirevwe** [comment]
Aha, I wanted to say that too but didn't want to be forward. Ok, Please update the issue.

**Comment by Subomi** [comment]
@jirevwe Done.
