### ISSUE TITLE
Convoy UI should redirect when no auth token exists. 

### ISSUE THREAD

**Issue by Subomi** [frain-dev/convoy#326]
Currently, the UI doesn't check if a token exists and doesn't redirect properly.

**Comment by horlah** [comment]
@Subomi There is specific error code you mentioned when you explained this to me, was it 400?

**Comment by horlah** [comment]
FE already handles 401 properly, reason for the bug is the BE returning 400.

That needs to be fixed.

**Comment by Subomi** [comment]
Both sides should do the checking. The FE is sending empty string. That shouldn't happen.

**Comment by horlah** [comment]
This is fixed on FE now, closing.
