### ISSUE TITLE
Correct Error Message for Malformed JSON Payload

### ISSUE THREAD

**Issue by Dotunj** [frain-dev/convoy#333]
At the moment, a generic error message is sent back to the client whenever there's something wrong with the request payload. To improve the experience of the API, we can return back to the client the appropriate error message when any of the following occurs:

- Empty Request Body
- Malformed Request Body
- Incorrect JSON type for a request field

**Comment by jirevwe** [comment]
@Dotunj is this the validator integration issue?

**Comment by Dotunj** [comment]
@jirevwe no it isn't. This is the validator issue #334
