### ISSUE TITLE
Support Static IPs

### ISSUE THREAD

**Issue by Subomi** [frain-dev/convoy#351]
Most security-driven APIs require static IPs, so companies can open their firewall to specific IP addresses. Enable Convoy support static IPs out-of-the-box.

Companies who implement this today - Coinbase, Stripe, Paystack.

**Comment by oneEyedSunday** [comment]
if I recall correctly we only support addresses (domain names) of the form `HTTP(s)://` right now? 

See https://github.com/frain-dev/convoy/pull/251/commits/c8e5efea497800ce99d6a952c6ec5c44faad0720

**Comment by Subomi** [comment]
No, this issue is for convoy to publish events only through pre-defined endpoints. Not the type of endpoint we support.

**Comment by oneEyedSunday** [comment]
Ok, can you show me what we currently support?

**Comment by Subomi** [comment]
We currently have no support for static IPs. Lol. I'd explain better at the meetup tomorrow. :)

**Comment by Subomi** [comment]
Hey @oneEyedSunday, this has shipped btw, but the current docs are lacking. We can discuss in slack about how it works. :)
