### ISSUE TITLE
Publish binary on package managers

### ISSUE THREAD

**Issue by Subomi** [frain-dev/convoy#354]
Enable developers to download convoy with package managers like `brew`, `apt`, `yum`, etc.

**Comment by Marvel-Ib** [comment]
@Dotunj  is it possible to work with you on this. 

not confident but definitely would love to help

**Comment by Dotunj** [comment]
@Marvel-Ib sure. I'm currently trying out different release tools to see how best to automate this. [Goreleaser](https://goreleaser.com/) seems to be a popular choice
