### ISSUE TITLE
Format numbers on dashboard

### ISSUE THREAD

**Issue by horlah** [frain-dev/convoy#442]
We're having long metrics numbers, we need to start adding comas to make them readable

**Comment by oneEyedSunday** [comment]
Looking like we'd need a custom pipe. The default number pipe supports just
decimal places

**Comment by horlah** [comment]
Yea... I've written something similar before.

**Comment by oneEyedSunday** [comment]
Apparently, https://stackoverflow.com/a/40661810/5134605 or https://stackoverflow.com/questions/40661634/formatting-a-number-to-have-commas-at-every-1000-factor#comment68554803_40661810 are easy fixes.

The first is preferable as it doesn't rely on locale.

**Comment by oneEyedSunday** [comment]
Should be fixed in https://github.com/frain-dev/convoy/pull/449
