### ISSUE TITLE
Installation script needs correction

### ISSUE THREAD

**Issue by mykeels** [frain-dev/convoy#599]
In the [README](https://github.com/frain-dev/convoy/blob/main/README.md#building-from-source), the installation script references a directory that does not exist.

```sh
go build -o convoy ./convoy
```

when it should be

```sh
go build -o convoy ./
```

**Comment by danvixent** [comment]
Thank you for pointing this out @mykeels, it's actually supposed to be
```bash
go build -o convoy ./cmd
```

**Comment by mykeels** [comment]
Aiite, thanks!
