### ISSUE TITLE
convoy.json file likely not being recognized

### ISSUE THREAD

**Issue by mykeels** [frain-dev/convoy#602]
We built a convoy.exe file, and copied the convoy.json contents with in-memory configuration from https://getconvoy.io/docs/guide/#2-copy-configuration

We tried to run the binary with `./convoy.exe server` and `./convoy.exe server --config ./convoy.json`, but kept getting:

```log
FATAL please provide the Redis DSN
```

It was only when we used:

```sh
./convoy.exe server --config ./convoy.json --queue in-memory
```

that the binary began running the server as expected, with an in-memory configuration.

Either the convoy.json file is not recognized, or the in-memory config in the file is not overriding the check for Redis DSN.

**Comment by danvixent** [comment]
@mykeels please what version are you attempting to run?

**Comment by mykeels** [comment]
I downloaded the source from the `main` branch, then built it somehow, and ran that.

**Comment by Subomi** [comment]
Hmm. That's weird because we fixed this in the release v0.5.x :( 

Try checking out from the `release-0.5` branch and build from source. We should cherry-pick that change to `main`.

**Comment by Subomi** [comment]
I was wrong. It was fixed in `main`. See #564 Adding the bug label.

**Comment by Subomi** [comment]
@mykeels, I just tested this again. We've fixed this in `main`.
