### ISSUE TITLE
Login page does not have placeholders

### ISSUE THREAD

**Issue by mykeels** [frain-dev/convoy#604]
I know it's probably Username and Password, but the absence of prompts could be easily fixed.

![image](https://user-images.githubusercontent.com/11996508/163580535-3b226090-4b71-4fc2-8653-4851bbbf11b2.png)

**Comment by Oluwadaminiola** [comment]
Hi @mykeels, what branch are you currently working with

**Comment by mykeels** [comment]
main

**Comment by Oluwadaminiola** [comment]
okay, just try and rebuild your UI with the following commands:
`# Enter UI directory
cd ./web/ui/dashboard

# Install dependencies
npm install

# Run production build
npm run build

# Copy build artifacts
cd ../../../
mv web/ui/dashboard/dist/* server/ui/build

# Build Binary
go build -o convoy ./cmd/*.go`
And then start your convoy instance again

**Comment by Oluwadaminiola** [comment]
hi @mykeels have you been able to resolve this
