### ISSUE TITLE
From the guide, we did not expect a login page

### ISSUE THREAD

**Issue by mykeels** [frain-dev/convoy#605]
We followed this guide, https://getconvoy.io/docs/guide, and was surprised when I got a login page.

We had to copy the credentials from the convoy.example.json file, to be able to login. 

I think the guide should be updated to reflect this.

**Comment by mykeels** [comment]
Actually, we are able to login by providing any credentials at all when `auth.require_auth` is `false`.

**Comment by Subomi** [comment]
Yeah, I noticed this bug earlier. Thanks for raising an issue.

**Comment by Subomi** [comment]
@mykeels This seems to have been fixed in `main` too. :)
