### ISSUE TITLE
Support DateTime filter

### ISSUE THREAD

**Issue by AnhHT** [frain-dev/convoy#648]
At the moment, convoy support filtering event and event deliveries by date range.
I expect to have a DateTime range filtering both in Chart and Table section
![Screen Shot 2022-05-09 at 17 45 37](https://user-images.githubusercontent.com/6800323/167394813-f086a0f2-23d3-423b-bdb4-2eb58101b396.png)
![Screen Shot 2022-05-09 at 17 45 23](https://user-images.githubusercontent.com/6800323/167394821-d8d9f7cb-be43-4c8c-9ef1-efa24e1e7289.png)
.

**Comment by Subomi** [comment]
@AnhHT The fix for this has been merged and will be out in the next release. 🌟
