### ISSUE TITLE
Optimise Groups N+1 Query

### ISSUE THREAD

**Issue by Subomi** [frain-dev/convoy#673]
Currently, loading groups have an `N+1` problem. It first loads the groups, and then calls `FillGroupStatistics` which runs a loop to retrieve each group's app count & event count. 

This result is the Group API timeouts in production.

**Comment by jirevwe** [comment]
Yeah, I mentioned this, we should use an aggregation to fetch all the information. Though do we really need to do it because we're not loading all the information for all the groups at the same time again.

**Comment by Subomi** [comment]
@jirevwe Hm. I think the optimisation is still better than what we currently have. We'd still need it for that view of the grid of groups (projects).
