### ISSUE TITLE
Allow a way to add a custom authorization headers to each payload sent to an application endpoint

### ISSUE THREAD

**Issue by nghialy** [frain-dev/convoy#713]
If an application endpoint is behind an authorization system, the payload to be sent to the endpoint needs to include an Authentication header. This header should be configurable for each application endpoint because each endpoint will require a different credential.

This can be solved by adding "custom_headers" for each application endpoint. This property specifies the list of headers to be included on each payload and will be useful for other application also aside from authentication.

It should look something like this in the API:
```
"models.Endpoint": {
    "properties": {
	  ...
          "custom_headers": {
              "items": {
                  "key": {
                      "type":"string"
                  },
                  "value": {
                       "type":"string"
                  }
              },
              "type":"array"
          }
           
    },
    "type": "object"
}
```

**Comment by Dotunj** [comment]
Hi @nghialy, we've added a generic way of sending custom headers with this PR #1012 which can we help with what you're trying to achieve here. Albeit, in subsequent updates we'll provide a separate feature to handle authorization for endpoints. An issue has been raised for it here. #1013
