### ISSUE TITLE
[BUG] Export fails to connect to an unauthenticated MongoDB instance.

### ISSUE THREAD

**Issue by Subomi** [frain-dev/convoy#970]
Image of current error response:
![Screenshot 2022-08-26 at 12 59 35 PM](https://user-images.githubusercontent.com/5220101/186898998-67ae6432-56a8-46d2-979a-1fee35f2761c.png)

**Comment by oneEyedSunday** [comment]
I set up a mongodb instance via docker-compose. I cannot reproduce this.
While setting up though, i did run into a similar issue because i had the ports wrong in my config.

**Comment by oneEyedSunday** [comment]
I ran the instance with

```sh
docker-compose -f noauth.yml -p convoy up -d
```

You can see my setup here 

https://github.com/frain-dev/convoy/compare/main...oneEyedSunday:convoy:bugfix/connect_unauthenticated_mongo

I think the convoy-docker.json is from earlier versions.

I did get a similar error from the image in this issue when i had the ports set to the values in test/docker-compose.yml
<img width="1169" alt="Screenshot 2022-08-29 at 10 05 09" src="https://user-images.githubusercontent.com/29808443/187165862-36c9ad82-43b1-4db7-9c31-92079bcdfa75.png">


<img width="739" alt="Screenshot 2022-08-29 at 10 01 35" src="https://user-images.githubusercontent.com/29808443/187165594-92c1fed9-37a6-4e0d-a0a0-ae064758421f.png">

<img width="1262" alt="Screenshot 2022-08-29 at 10 01 44" src="https://user-images.githubusercontent.com/29808443/187165728-020a85bf-a013-415a-b907-1b21e6c69ce3.png">
